# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "P7dR8mSH"
    curseforge: "306612"
  license: Apache-2.0
  fileType: jar
  md5: d49d5295bacd1a0e31f0de624f1f2530
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabric-api/version/5b23omah
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3494349
    sourceControl: https://github.com/FabricMC/fabric/releases/tag/0.41.0%2B1.17
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/P7dR8mSH/versions/0.41.0+1.17/fabric-api-0.41.0+1.17.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3494349/file
    sourceControl: https://github.com/FabricMC/fabric/releases/download/0.41.0%2B1.17/fabric-api-0.41.0+1.17.jar
    others: ~
