# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: PaperMC.starlight
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "hEOCdOgW"
    curseforge: "372124"
  license: LGPL-3.0-only
  fileType: jar
  md5: dc00c550ee486edeacc670b0f8d3e9ab
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/phosphor/version/C9Witfc8
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/files/3202749
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/tag/mc1.16.2-v0.7.1
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/hEOCdOgW/versions/mc1.16.2-0.7.1/phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/download/3202749/file
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/download/mc1.16.2-v0.7.1/phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
    others: ~
