# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: PaperMC.starlight
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "hEOCdOgW"
    curseforge: "372124"
  license: LGPL-3.0-only
  fileType: jar
  md5: 4fb7a4b06cd53947432e65e3a8c9a5ce
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/phosphor/version/tFQASSAx
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/files/3141950
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/tag/mc1.16.2-v0.7.0
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/hEOCdOgW/versions/mc1.16.3-0.7.0/phosphor-fabric-mc1.16.3-0.7.0+build.10.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/download/3141950/file
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/download/mc1.16.2-v0.7.0/phosphor-fabric-mc1.16.3-0.7.0+build.10.jar
    others: ~
