# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "gvQqBUqZ"
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: 9e5094170a6ec26983d792ad2c2a8a72
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/lithium/version/5fmGl08Y
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3179373
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.5-0.6.1
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.16.5-v0.6.1/lithium-fabric-mc1.16.5-0.6.1.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3179373/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.5-0.6.1/lithium-fabric-mc1.16.5-0.6.1.jar
    others: ~
