# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "gvQqBUqZ"
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: 73c3cb0bbd04efe2c88d04dee58dbb74
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/lithium/version/pGhOMdTm
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3343357
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.5-0.6.5
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.16.5-0.6.5/lithium-fabric-mc1.16.5-0.6.5.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3343357/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.5-0.6.5/lithium-fabric-mc1.16.5-0.6.5.jar
    others: ~
