# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "P7dR8mSH"
    curseforge: "306612"
  license: Apache-2.0
  fileType: jar
  md5: 919cf187e3b5963d74c140203ad9a65c
  downloadPageUrls:
    modrinth: https://modrinth.org/mod/fabric-api/version/nSk00F5M
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3358619
    sourceControl: https://github.com/FabricMC/fabric/releases/tag/0.36.0%2B1.17
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/P7dR8mSH/versions/0.36.0+1.17/fabric-api-0.36.0+1.17.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3358619/file
    sourceControl: https://github.com/FabricMC/fabric/releases/download/0.36.0%2B1.17/fabric-api-0.36.0+1.17.jar
    others: ~
