# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: Biom4st3r
iconUrls:
  - https://media.forgecdn.net/avatars/372/542/637543695507572259.png
status: active
updatedAlternatives: ~
name: RecipeCache
description: Caches the previous recipe to dramatically increase performance of crafting
authors:
  - name: Biom4st3r
home: https://gitlab.com/biom4st3r
source: https://gitlab.com/biom4st3r/optimizedcrafting
issues: https://gitlab.com/biom4st3r/optimizedcrafting/-/issues
support: https://gitlab.com/biom4st3r/optimizedcrafting/-/issues/service_desk
wiki: ~
chats:
  discord: ~
  irc: ~
  others: ~
versions:
  - version: "0.2.1"
  - version: "0.2.0"
  - version: "0.1.0"
