# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: shedaniel
iconUrls:
  - https://media.forgecdn.net/avatars/thumbnails/282/468/64/64/637289313152268031.png
status: active
updatedAlternatives: ~
name: Cloth Config v5
description: An API for config screens.
authors:
  - name: shedaniel
home: https://www.curseforge.com/minecraft/mc-mods/cloth-config
source: https://github.com/shedaniel/ClothConfig
issues: https://github.com/shedaniel/ClothConfig/issues
support: https://discord.com/invite/Vs9AVkxjYY
wiki: https://shedaniel.gitbook.io/cloth-config/
chats:
  discord: https://discord.com/invite/Vs9AVkxjYY
  irc: ~
  others: ~
versions:
  - version: "5.1.40"
  - version: "4.12.41"
