# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends:
    - packageId: BradBot_1.bfapi
      version: ">=1.1.6"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "eM1KzRjc"
    curseforge: "480257"
  license: Apache-2.0
  fileType: jar
  md5: 169497f56a4ec452c06b6b298cf37a8d
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/sit/version/W0rB9c1E
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabricsit/files/3404512
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/eM1KzRjc/versions/v1.6.0/FabricSit-1.6.0.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabricsit/download/3404512/file
    sourceControl: ~
    others: ~
