# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: bc009cde08a8169513f4c3b7b9404571
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3042177
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.2-0.5.2
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3042177/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.2-0.5.2/lithium-fabric-mc1.16.2-0.5.2.jar
    others: ~
