# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.3"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: e5056c64627dddbd8a5646db394f7d52
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3061511
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.3-0.5.5
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3061511/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.3-0.5.5/lithium-fabric-mc1.16.3-0.5.5.jar
    others: ~
