# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.1"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: 7f497a5467031a4b739cd220614b5e0b
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/2996131
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.1-0.5.0
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/2996131/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.1-0.5.0/lithium-fabric-mc1.16.1-0.5.0.jar
    others: ~
