# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.3"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: e4865322bd77943ac0961177c7d5d092
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3063230
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.3-0.5.6
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3063230/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.3-0.5.6/lithium-fabric-mc1.16.3-0.5.6.jar
    others: ~
