# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.2"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: 3a3b3e10e7a753f888a6e0492c97437f
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3046951
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.2-0.5.4
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3046951/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.2-0.5.4/lithium-fabric-mc1.16.2-0.5.4.jar
    others: ~
