# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: ramidzkh
iconUrls:
  - https://cdn.modrinth.com/data/3qsfQtE9/icon.png
  - https://media.forgecdn.net/avatars/thumbnails/335/447/64/64/637470408666855956.png
status: active
updatedAlternatives: ~
name: Fabricshot
description: Take high resolution screenshots because why not
authors:
  - name: ramidzkh
home: https://www.curseforge.com/minecraft/mc-mods/fabrishot
source: https://github.com/ramidzkh/fabrishot
issues: https://github.com/ramidzkh/fabrishot/issues
support: ~
wiki: ~
chats:
  discord: ~
  irc: ~
  others: ~
versions:
  - version: "1.5.1"
  - version: "1.4.0"
