# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: unsupported
    client: required
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: NuclearFarts.connected_block_textures
      version: "*"
    - packageId: FoundationGames.enhancedblockentities
      version: "*"
    - packageId: Chocohead.optifabric
      version: "*"
    - packageId: CaffeineMC.sodium
      version: "<=0.1.0"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "ZfQ3kTvR"
    curseforge: "472772"
  license: LGPL-3.0-only
  fileType: jar
  md5: 27e9a8930f07c19af53159bdc474e3de
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/dashloader/version/IbL8S9Tt
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dashloader/files/3484075
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/ZfQ3kTvR/versions/2.0.1/dashloader-2.0.1.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dashloader/download/3484075/file
    sourceControl: ~
    others: ~
