# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: dfsek
iconUrls:
  - https://cdn.modrinth.com/data/FIlZB9L0/icon.png
  - https://raw.githubusercontent.com/PolyhedralDev/Terra/ver/6.0.0/platforms/fabric/src/main/resources/assets/terra/icon.png
status: active
updatedAlternatives: ~
name: Terra
description: A fast, modern, extensible, platform-agnostic data-driven world generator
authors:
  - name: dfsek
home: https://github.com/PolyhedralDev/Terra/wiki
source: https://github.com/PolyhedralDev/Terra
issues: https://github.com/PolyhedralDev/Terra/issues
support: https://discord.gg/PXUEbbF
wiki: https://github.com/PolyhedralDev/Terra/wiki
chats:
  discord: https://discord.gg/PXUEbbF
  irc: ~
  others: ~
versions:
  - version: "6.0.0-BETA"
  - version: "5.4.1-BETA"
  - version: "5.3.3-BETA"
