# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17"
  environment:
    server: optional
    client: optional
  channel: beta
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "AZomiSrC"
    curseforge: ~
  license: LGPL-3.0-only
  fileType: jar
  md5: 9165d6cc0b5f60f5ad94eebfdb86d493
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/hydrogen/version/nc84mXki
    curseforge: ~
    sourceControl: https://github.com/CaffeineMC/hydrogen-fabric/releases/tag/mc1.17-0.3.0
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/AZomiSrC/versions/mc1.17-v0.3.0/hydrogen-fabric-mc1.17-0.3.jar
    curseforge: ~
    sourceControl: https://github.com/CaffeineMC/hydrogen-fabric/releases/download/mc1.17-0.3.0/hydrogen-fabric-mc1.17-0.3.jar
    others: ~
