# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends:
    - packageId: FabricMC.fabric
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "q1O2IGx6"
    curseforge: ~
  license: ISC
  fileType: jar
  md5: b1ccd817f7fa7cfb4b7936c85ed4f6af
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabriccrossdimtpfix/version/hFa4excN
    curseforge: ~
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/q1O2IGx6/versions/v0.2.0/fabriccrossdimtpfix-0.2.0.jar
    curseforge: ~
    sourceControl: ~
    others: ~
