# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: unsupported
    client: required
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "319057"
  license: GNU LGPLv3
  fileType: jar
  md5: df1ce18a2d177145067a66df0c87f4f0
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3521267
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/cloth-config/download/3521267/file
    sourceControl: ~
    others: ~
