# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "gvQqBUqZ"
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: a2e966bfe3173327c3874236a23fa6e5
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/lithium/version/aZ0JFf08
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3359899
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.17-0.7.2
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17-0.7.2/lithium-fabric-mc1.17-0.7.2.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3359899/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.17-0.7.2/lithium-fabric-mc1.17-0.7.2.jar
    others: ~
