# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.18.1"
    - "1.18"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "gvQqBUqZ"
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: 78db5a281defce0ccd4ef27b1be3fb58
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/lithium/version/2CbyxeU0
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3565566
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.18.1-0.7.6
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.1-0.7.6/lithium-fabric-mc1.18.1-0.7.6.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3565566/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.18.1-0.7.6/lithium-fabric-mc1.18.1-0.7.6.jar
    others: ~
