# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks:
    - packageId: Chocohead.optifabric
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "gvQqBUqZ"
    curseforge: "360438"
  license: LGPL-3.0-only
  fileType: jar
  md5: a66d363e0da033c98a43986a3183ef2a
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/lithium/version/FHFKMKeu
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3516367
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.17.1-0.7.5
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17.1-0.7.5/lithium-fabric-mc1.17.1-0.7.5.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3516367/file
    sourceControl: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.17.1-0.7.5/lithium-fabric-mc1.17.1-0.7.5.jar
    others: ~
