# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: f85e752e083bdcd827309769b1d78447
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/al1ek4A1
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3411174
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.7/BFAPI-v1-1-7.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3411174/file
    sourceControl: ~
    others: ~
