# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: bacc260f722579ba3c6dc1dc29464fe8
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/9QCIJOVz
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3425333
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.8/BFAPI-V1-1-8.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3425333/file
    sourceControl: ~
    others: ~
