# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: edeb3d976b45ae900b1e9220d4616842
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/IQOhgNHA
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3382978
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.4/BFAPI-v1-1-4.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3382978/file
    sourceControl: ~
    others: ~
