# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: 75ec8678302e15a6b4442146fee7ebc3
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/2NvOf5qS
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3404507
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/1.1.6/BFAPI-v1-1-6.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3404507/file
    sourceControl: ~
    others: ~
