# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends:
    - packageId: FabricMC.fabric
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: e6aa59b2153a22daf1f4ae9c779914ca
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/53hFdjWY
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3378666
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.1/BFAPI-1.1.1.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3378666/file
    sourceControl: ~
    others: ~
