# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: 6f46b55a5f0756501dedc3c4f7c805c2
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/Uw3BpwYk
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3509878
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.11/BradsFabricApi-1.1.11.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3509878/file
    sourceControl: ~
    others: ~
