# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "toILlMg6"
    curseforge: "501198"
  license: Apache-2.0
  fileType: jar
  md5: e722ba68bbb83b39ef25e3b6c155adc9
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/bfapi/version/aJvwyNek
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/files/3378734
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/toILlMg6/versions/v1.1.2/BFAPI-1-1-2.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/bfapi/download/3378734/file
    sourceControl: ~
    others: ~
