# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: required
    client: optional
  channel: beta
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "FIlZB9L0"
    curseforge: "450465"
  license: GPL-3.0
  fileType: jar
  md5: a9ed16e69d41d19fb7bc2a3da0129db8
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/terra/version/i38N6tkR
    curseforge: ~
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/FIlZB9L0/versions/5.4.1-BETA+40e95073/Terra-fabric-5.4.1-BETA+40e95073-shaded-mapped.jar
    curseforge: ~
    sourceControl: ~
    others: ~
