# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
    - "1.16.1"
    - "1.16"
    - "1.15.2"
    - "1.15.1"
    - "1.15"
    - "1.14.4"
    - "1.14.3"
    - "1.14.2"
    - "1.14.1"
    - "1.14"
  environment:
    server: required
    client: unsupported
  channel: release
  depends:
    - packageId: FabricMC.fabric
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "FCmig1C9"
    curseforge: "318315"
  license: MIT
  fileType: jar
  md5: fcc7ea5564b51f22d124845c87b7dc47
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabric-discord-link/version/FNKQtuHn
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/3452563
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com//data/FCmig1C9/versions/0.9.7/Fabric-Discord-Link-0.9.7.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/download/3452563/file
    sourceControl: ~
    others: ~
