# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: ReviversMC
iconUrls:
  - https://cdn.modrinth.com/data/2NpFE0R3/icon.png
  - https://media.forgecdn.net/avatars/440/791/637689758078915759.png
  - https://raw.githubusercontent.com/ReviversMC/modget-minecraft/master/src/main/resources/assets/modget/icon.png
status: active
updatedAlternatives: ~
name: Modget
description: The Minecraft Mod Package Manager! Can install mods via commands, search for updates and much more.
authors:
  - name: NebelNidas
home: https://github.com/ReviversMC/modget
source: https://github.com/ReviversMC/modget
issues: https://github.com/ReviversMC/modget/issues
support: https://discord.gg/nVDXfCRyMk
wiki: https://github.com/ReviversMC/modget/blob/master/README.md
chats:
  discord: https://discord.gg/nVDXfCRyMk
  irc: ~
  others: ~
versions:
  - version: "0.3.0"
  - version: "0.2.3"
  - version: "0.2.2"
  - version: "0.2.0"
