# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: EnnuiL
iconUrls:
  - https://cdn.modrinth.com/data/aXf2OSFU/icon.png
  - https://media.forgecdn.net/avatars/239/419/637113788236894456.png
  - https://raw.githubusercontent.com/EnnuiL/OkZoomer/1.17/src/main/resources/assets/okzoomer/icon.png
status: active
updatedAlternatives: ~
name: OkZoomer
description: Adds a highly configurable zoom button. By default, this mod provides its own take on zooming, however, with configuration, you can drastically change the zoom with something more familiar or useful. The zoom is yours!
authors:
  - name: EnnuiL
home: https://www.curseforge.com/minecraft/mc-mods/ok-zoomer
source: https://github.com/EnnuiL/OkZoomer
issues: https://github.com/EnnuiL/OkZoomer/issues
support: https://github.com/EnnuiL/OkZoomer/issues
wiki: ~
chats:
  discord: ~
  irc: ~
  others: ~
versions:
  - version: "5.0.0-beta.3"
  - version: "5.0.0-beta.2"
  - version: "4.0.1"
