# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: unsupported
    client: required
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends:
    - packageId: TerraformersMC.modmenu
      version: ">2.0.0"
  thirdPartyIds:
    modrinth: ~
    curseforge: "408209"
  license: MIT
  fileType: jar
  md5: 95e7b82b78a5583eb5d3baa22630a0df
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen/files/3470993
    sourceControl: https://github.com/A5b84/dark-loading-screen/releases/tag/v1.6.11
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen/download/3470993/file
    sourceControl: https://github.com/A5b84/dark-loading-screen/releases/download/v1.6.11/dark-loading-screen-1.6.11.jar
    others: ~
