# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "473492"
  license: MIT
  fileType: jar
  md5: 36e74c104abee8763249d8e3475acb05
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/recipe-cache/files/3369522
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/recipe-cache/download/3369522/file
    sourceControl: ~
    others: ~

- loaders:
    - fabric
  minecraftVersions:
    - "1.17"
  environment:
    server: required
    client: unsupported
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "473492"
  license: MIT
  fileType: jar
  md5: 2c6b6f29defdb471c2732aaaf69a0f8f
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/recipe-cache/files/3348298
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/recipe-cache/download/3348298/file
    sourceControl: ~
    others: ~
