manifestSpecVersion: 3.1
publisher: CaffeineMC
id: sodium
loader:
  - fabric
modType: jar
side: client
name: Sodium
description: Sodium is a free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.
license: LGPL-3.0-only
home: https://caffeinemc.net
source: https://github.com/CaffeineMC/sodium-fabric
issues: https://github.com/CaffeineMC/sodium-fabric/issues
chat: https://jellysquid.me/discord
breaks:
  - package: Chocohead.optifabric
    version: "*"
  - package: vram-guild.canvas
    version: "*"
thirdPartyIds:
  modrinth: AANobbMI
  curseforge: 394468
downloads:
  - version: 0.3.2
    depends:
      - package: FabricMC.fabric
        version: "*"
    minecraftVersions:
      - 1.17.1
    md5: b88cf07d124c5b96b82ab27e51fdff04
    downloadPageUrls:
      - name: Modrinth
        url: https://modrinth.com/mod/sodium/version/xuWxRZPd
      - name: GitHub
        url: https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.2
    fileUrls:
      - name: Modrinth
        url: https://cdn.modrinth.com/data/AANobbMI/versions/mc1.17.1-0.3.2/sodium-fabric-mc1.17.1-0.3.2+build.7.jar
      - name: GitHub
        url: https://github.com/CaffeineMC/sodium-fabric/releases/download/mc1.17.1-0.3.2/sodium-fabric-mc1.17.1-0.3.2+build.7.jar
  - version: 0.2.0
    minecraftVersions:
      - 1.16.2
      - 1.16.3
      - 1.16.4
      - 1.16.5
    # Although versions 1.16.2 to 1.16.4 aren't officially compatible, they have been tested by NebelNidas and confirmed working by CaffeineMC's discord server.
    md5: 98914f22cfe2d0ea5d8007ae8ff96062
    downloadPageUrls:
      - name: Modrinth
        url: https://modrinth.com/mod/sodium/version/YAGZ1cCS
      - name: GitHub
        url: https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.16.5-0.2.0
    fileUrls:
      - name: Modrinth
        url: https://cdn.modrinth.com/data/AANobbMI/versions/mc1.16.5-0.2.0/sodium-fabric-mc1.16.5-0.2.0+build.4.jar
      - name: GitHub
        url: https://github.com/CaffeineMC/sodium-fabric/releases/download/mc1.16.5-0.2.0/sodium-fabric-mc1.16.5-0.2.0+build.4.jar
