# yaml-language-server: $schema=../../../../doc/validation-schemas/4.0/main-manifest.json

manifestSpecVersion: "4.0"
publisher: CaffeineMC
iconUrls:
  - https://cdn.modrinth.com/data/AANobbMI/icon.png
  - https://media.forgecdn.net/avatars/284/773/637298471098686391.png
  - https://raw.githubusercontent.com/CaffeineMC/sodium-fabric/1.17.x/dev/src/main/resources/assets/sodium/icon.png
status: active
updatedAlternatives: ~
name: Sodium
description: Sodium is a free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.
authors:
  - name: JellySquid
home: https://caffeinemc.net
source: https://github.com/CaffeineMC/sodium-fabric
issues: https://github.com/CaffeineMC/sodium-fabric/issues
support: https://jellysquid.me/discord
wiki: ~
chats:
  discord: https://jellysquid.me/discord
  irc: ~
  others: ~
versions:
  - version: "0.4.0-alpha5"
  - version: "0.3.3"
  - version: "0.3.2"
  - version: "0.2.0"
