# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.18.1"
    - "1.18"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "P7dR8mSH"
    curseforge: "306612"
  license: Apache-2.0
  fileType: jar
  md5: 02d2082af80a1582bc9b2b2472046a86
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabric-api/version/RSZHmY2f
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3546679
    sourceControl: https://github.com/FabricMC/fabric/releases/tag/0.44.0%2B1.18
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/P7dR8mSH/versions/0.44.0+1.18/fabric-api-0.44.0+1.18.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3546679/file
    sourceControl: https://github.com/FabricMC/fabric/releases/download/0.44.0%2B1.18/fabric-api-0.44.0+1.18.jar
    others: ~

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "P7dR8mSH"
    curseforge: "306612"
  license: Apache-2.0
  fileType: jar
  md5: d6666ca4430a0d4334efec7ebb4d449d
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabric-api/version/ruKoLG2a
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3546670
    sourceControl: https://github.com/FabricMC/fabric/releases/tag/0.44.0%2B1.17
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/P7dR8mSH/versions/0.44.0+1.17/fabric-api-0.44.0+1.17.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3546670/file
    sourceControl: https://github.com/FabricMC/fabric/releases/download/0.44.0%2B1.17/fabric-api-0.44.0+1.17.jar
    others: ~
