# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
    - "1.16.1"
    - "1.16"
  environment:
    server: unsupported
    client: required
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "332523"
  license: Apache-2.0
  fileType: jar
  md5: 2135fedb77bc0c8de377bd2738b52794
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/clear-skies/files/3319590
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/clear-skies/download/3319590/file
    sourceControl: ~
    others: ~
