# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.17.1"
    - "1.17"
  environment:
    server: unsupported
    client: required
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "332523"
  license: Apache-2.0
  fileType: jar
  md5: 3d7a6f7f9d42e7597a7a7fba52161d38
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/clear-skies/files/3399879
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/clear-skies/download/3399879/file
    sourceControl: ~
    others: ~
