manifestSpecVersion: 3.1
publisher: CaffeineMC
id: lithium
loader:
  - fabric
modType: jar
side: server
name: Lithium
description: Lithium is a free and open-source optimization mod for Minecraft which makes a wide range of performance improvements to the game.
license: LGPL-3.0-only
home: https://caffeinemc.net
source: https://github.com/CaffeineMC/lithium-fabric
issues: https://github.com/CaffeineMC/lithium-fabric/issues
wiki: https://github.com/CaffeineMC/lithium-fabric/wiki
chat: https://jellysquid.me/discord
breaks:
  - package: Chocohead.optifabric
    version: "*"
thirdPartyIds:
  modrinth: gvQqBUqZ
  curseforge: 360438
downloads:
  - version: 0.7.4
    minecraftVersions:
      - 1.17.0
      - 1.17.1
    md5: 5e9a9c1dfaa4e10403a8c658639e5cca
    downloadPageUrls:
      - name: Modrinth
        url: https://modrinth.com/mod/lithium/version/nVR7Q63z
      - name: GitHub
        url: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.17.1-0.7.4
      - name: CurseForge
        url: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3438799
    fileUrls:
      - name: Modrinth
        url: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17.1-0.7.4/lithium-fabric-mc1.17.1-0.7.4.jar
      - name: GitHub
        url: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.17.1-0.7.4/lithium-fabric-mc1.17.1-0.7.4.jar
      - name: CurseForge
        url: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3438799/file
  - version: 0.6.6
    minecraftVersions:
      - 1.16.2
      - 1.16.3
      - 1.16.4
      - 1.16.5
    md5: 19f9a82b0753ae21430761a8916f0533
    downloadPageUrls:
      - name: Modrinth
        url: https://modrinth.com/mod/lithium/version/rvsW1zhb
      - name: GitHub
        url: https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.16.5-0.6.6
      - name: CurseForge
        url: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3344974
    fileUrls:
      - name: Modrinth
        url: https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.16.5-0.6.6/lithium-fabric-mc1.16.5-0.6.6.jar
      - name: GitHub
        url: https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.16.5-0.6.6/lithium-fabric-mc1.16.5-0.6.6.jar
      - name: CurseForge
        url: https://www.curseforge.com/minecraft/mc-mods/lithium/download/3344974/file
