# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
    - "1.16.1"
    - "1.16"
  environment:
    server: optional
    client: optional
  channel: alpha
  depends: ~
  bundles: ~
  breaks:
    - packageId: CaffeineMC.phosphor
      version: "*"
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: ~
  license: LGPL-3.0-only
  fileType: jar
  md5: d19207042c3a22c553ec053cc483c978
  downloadPageUrls:
    modrinth: ~
    curseforge: ~
    sourceControl: https://github.com/PaperMC/Starlight/releases/tag/1.0.0-RC2
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: ~
    sourceControl: https://github.com/PaperMC/Starlight/releases/download/1.0.0-RC2/starlight-fabric-1.0.0-RC2-1.16.x.jar
    others: ~
