# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
    - "1.16.1"
    - "1.16"
  environment:
    server: optional
    client: optional
  channel: beta
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "372124"
  license: LGPL-3.0-only
  fileType: jar
  md5: 7f1e015a7ef9f53fd93b3f348ca85766
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2918212
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/tag/mc20w13b-v0.5.1
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/download/2918212/file
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/download/mc20w13b-v0.5.1/phosphor-fabric-mc20w13b-0.5.1+build.3.jar
    others: ~

- loaders:
    - fabric
  minecraftVersions:
    - "1.15.2"
    - "1.15.1"
    - "1.15"
  environment:
    server: optional
    client: optional
  channel: release
  depends: ~
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: ~
    curseforge: "372124"
  license: LGPL-3.0-only
  fileType: jar
  md5: d36c81d6d090b29a74e3cab64f6aedea
  downloadPageUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2918208
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/tag/mc1.15.2-v0.5.1
    others: ~
  fileUrls:
    modrinth: ~
    curseforge: https://www.curseforge.com/minecraft/mc-mods/phosphor/download/2918208/file
    sourceControl: https://github.com/CaffeineMC/phosphor-fabric/releases/download/mc1.15.2-v0.5.1/phosphor-fabric-mc1.15.2-0.5.1+build.4.jar
    others: ~
