# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.16.5"
    - "1.16.4"
    - "1.16.3"
    - "1.16.2"
    - "1.16.1"
    - "1.16"
  environment:
    server: unsupported
    client: required
  channel: release
  depends:
    - packageId: FabricMC.fabric
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends:
    - packageId: TerraformersMC.modmenu
      version: ">1.0.0"
    - packageId: shedaniel.cloth-config2
      version: ">4.0.0"
  thirdPartyIds:
    modrinth: "3qsfQtE9"
    curseforge: "404870"
  license: MIT
  fileType: jar
  md5: 06f6345df6831303474346c6e30f48c9
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/fabrishot/version/YyQfKVvE
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabrishot/files/3271155
    sourceControl: ~
    others: ~
  fileUrls:
    modrinth: https://cdn.modrinth.com/data/3qsfQtE9/versions/1.4.0/fabrishot-1.4.0.jar
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fabrishot/download/3271155/file
    sourceControl: ~
    others: ~
