# yaml-language-server: $schema=../../../../../../doc/validation-schemas/4.0/version-manifest.json

- loaders:
    - fabric
  minecraftVersions:
    - "1.18"
    - "1.17.1"
    - "1.17"
  environment:
    server: unsupported
    client: required
  channel: release
  depends:
    - packageId: FabricMC.fabric
      version: "*"
  bundles: ~
  breaks: ~
  conflicts: ~
  recommends: ~
  thirdPartyIds:
    modrinth: "LQ3K71Q1"
    curseforge: "335493"
  license: MIT
  fileType: jar
  md5: 16b601d42126586465ccc5be23226f19
  downloadPageUrls:
    modrinth: https://modrinth.com/mod/dynamic-fps/version/Co2w6nIh
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/files/3497287
    sourceControl: https://github.com/juliand665/Dynamic-FPS/releases/tag/2.0.6
    others: ~
  fileUrls:
    modrinth: https://github.com/juliand665/Dynamic-FPS/releases/tag/2.0.6
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/download/3497287/file
    sourceControl: https://github.com/juliand665/Dynamic-FPS/releases/download/2.0.6/dynamic-fps-2.0.6.jar
    others: ~
